### ISSUE TITLE
Ошибка при индексации

### ISSUE THREAD

**Issue by ctac22** [webber12/evoSearch#17]
При попытке сохранить ресурс получаю ошибку
`Warning: file_get_contents(C:/OpenServer/domains/mysite/www/assets/lib/phpmorphy/dicts\common_aut..bin): failed to open stream: No such file or directory in C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\storage.php on line 138

Fatal error: Uncaught phpMorphy_Exception: Can`t read C:/OpenServer/domains/mysite/www/assets/lib/phpmorphy/dicts\common_aut..bin file in C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\storage.php:139 Stack trace: #0 C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\storage.php(34): phpMorphy_Storage_Mem->open('C:/OpenServer/d...') #1 C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\storage.php(209): phpMorphy_Storage->__construct('C:/OpenServer/d...') #2 C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\common.php(588): phpMorphy_Storage_Factory->open('mem', 'C:/OpenServer/d...', false) #3 C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\common.php(644): phpMorphy->initNewStyle(Object(phpMorphy_FilesBundle), Array) #4 C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\common.php(194): phpMorphy->initOldStyle(Object(phpMorphy_FilesBundle), Array) #5 C:\OpenServer\domains\mysite\www\assets\plugins\evoSearch\plugin.class.php(76): phpMorphy->__constr in C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\src\storage.php on line 139`

Версия EVO |   | 1.4.1
PHP 7.1

**Comment by webber12** [comment]
А сама папка assets/lib/phpmorphy/ скачалась?

**Comment by ctac22** [comment]
Папка phpmorphy с файлами есть. Я так понимаю должны подключаться файлы common_aut.en_en.bin  либо common_aut.ru_ru.bin (они есть в C:\OpenServer\domains\mysite\www\assets\lib\phpmorphy\dicts), а поиск пытается подключить common_aut..bin, т.е. локаль где-то теряется.
